require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.startup"
require "user.indent-blankline"
require "user.treesitter"
require "user.true-zen"
require "user.git-blame"

vim.cmd "colorscheme onedark"
vim.cmd "set nowrap"
