require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.startup"

vim.cmd "colorscheme catppuccin"
vim.cmd "set nowrap"
vim.cmd "hi normal guibg=000000"
